on:
  pull_request:
    
name: CI

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cashapp/activate-hermit@v1
    - name: Install dependencies
      run: just pnpm-install
    - name: Lint
      run: just lint-frontend
    - name: Build
      run: just build-frontend
